---
# Galaxy metadata for the harvester role
# This file is used when publishing to Ansible Galaxy

namespace: bpmconsultag
name: harvester
version: 1.0.5

readme: README.md

authors:
  - bpmconsultag

description: Ansible collection for managing SUSE Harvester HCI resources including custom modules for VMs, images, volumes, and networks

license: MIT

tags:
  - harvester
  - hci
  - virtualization
  - vm
  - suse
  - infrastructure
  - cloud
  - kubernetes

dependencies: {}

repository: https://github.com/bpmconsultag/harvester
documentation: https://github.com/bpmconsultag/harvester
homepage: https://github.com/bpmconsultag/harvester
issues: https://github.com/bpmconsultag/harvester/issues

build_ignore:
  - .git
  - .github
  - .gitignore
  - .ansible-lint
  - examples
  - tests
  - "*.pyc"
  - __pycache__
  - "*.swp"
  - "*.swo"
  - "*~"
  - .DS_Store
  - Thumbs.db
