---
# Example playbook: Clean up Harvester resources
- name: Delete Harvester resources
  hosts: localhost
  gather_facts: false
  vars:
    # Harvester settings will be loaded from .env file


  pre_tasks:
    - name: Load Harvester settings from environment variables (use dotenv to export before running)
      set_fact:
        harvester_host: "{{ lookup('ansible.builtin.env', 'HARVESTER_HOST') }}"
        harvester_token: "{{ lookup('ansible.builtin.env', 'HARVESTER_TOKEN') }}"
        harvester_namespace: "{{ lookup('ansible.builtin.env', 'HARVESTER_NAMESPACE') | default('default') }}"
        harvester_verify_ssl: "{{ lookup('ansible.builtin.env', 'HARVESTER_VERIFY_SSL') | default('true') }}"
  
  tasks:
    - name: Delete virtual machine
      bpmconsultag.harvester.harvester_vm:
        host: "{{ harvester_host }}"
        token: "{{ harvester_token }}"
        name: "my-ubuntu-vm"
        namespace: "{{ harvester_namespace }}"
        state: absent
      register: vm_delete_result
      ignore_errors: true

    - name: Delete volume
      bpmconsultag.harvester.harvester_volume:
        host: "{{ harvester_host }}"
        token: "{{ harvester_token }}"
        name: "my-vm-disk"
        namespace: "{{ harvester_namespace }}"
        state: absent
      register: volume_delete_result
      ignore_errors: true

    - name: Delete image
      bpmconsultag.harvester.harvester_image:
        host: "{{ harvester_host }}"
        token: "{{ harvester_token }}"
        name: "ubuntu-20.04"
        namespace: "{{ harvester_namespace }}"
        state: absent
      register: image_delete_result
      ignore_errors: true

    - name: Display cleanup results
      debug:
        msg: "Cleanup completed"
