---
# Example playbook: Create a virtual machine in Harvester
- name: Create and manage Harvester VM
  hosts: localhost
  gather_facts: false
  vars:
    # Harvester settings will be loaded from .env file
    vm_name: "my-ubuntu-vm7"


  pre_tasks:
    - name: Load Harvester settings from environment variables (use dotenv to export before running)
      set_fact:
        harvesterpy_host: "{{ lookup('ansible.builtin.env', 'HARVESTER_HOST') }}"
        harvesterpy_token: "{{ lookup('ansible.builtin.env', 'HARVESTER_TOKEN') }}"
        harvester_namespace: "{{ lookup('ansible.builtin.env', 'HARVESTER_NAMESPACE') | default('default') }}"
        harvester_verify_ssl: "{{ lookup('ansible.builtin.env', 'HARVESTER_VERIFY_SSL') | default('true') }}"
        harvester_network: "{{ lookup('ansible.builtin.env', 'HARVESTER_NETWORK') | default('br-clients') }}"
  
  tasks:
    - name: Create an image for the VM
      harvester_image:
        host: "{{ harvesterpy_host }}"
        token: "{{ harvesterpy_token }}"
        name: "ubuntu-24.04"
        namespace: "{{ harvester_namespace }}"
        state: present
        url: "https://cloud-images.ubuntu.com/releases/noble/release/ubuntu-24.04-server-cloudimg-amd64.img"
        display_name: "Ubuntu 24.04 LTS"
        description: "Ubuntu 24.04 cloud image"
        verify_ssl: "{{ harvester_verify_ssl }}"
      register: image_result

    - name: Create a volume for the VM
      harvester_volume:
        host: "{{ harvesterpy_host }}"
        token: "{{ harvesterpy_token }}"
        name: "{{ vm_name }}-disk"
        namespace: "{{ harvester_namespace }}"
        state: present
        storage: "10Gi"
        access_modes:
          - ReadWriteMany
        volume_mode: Block
        storage_class: "longhorn-ubuntu-24.04"
        volume_name: ""
        labels: {}
        image: "ubuntu-24.04-server-cloudimg-amd64-lvm.img"
        verify_ssl: "{{ harvester_verify_ssl }}"
      register: volume_result

    - name: Debug HARVESTER_NETWORK
      debug:
        msg: "HARVESTER_NETWORK is {{ lookup('env', 'HARVESTER_NETWORK') }}"

    - name: Create a virtual machine
      harvester_vm:
        debug: true
        host: "{{ harvesterpy_host }}"
        token: "{{ harvesterpy_token }}"
        name: "{{ vm_name }}"
        namespace: "{{ harvester_namespace }}"
        state: present
        running: true
        cpu_cores: 2
        memory: "4Gi"
        disks:
          - name: disk0
            volume_name: "{{ vm_name }}-disk"
            bus: virtio
        interfaces:
          - bridge: {}
            model: virtio
            name: default
        networks:
          - name: "default"
            multus:
              networkName: "default/{{ harvester_network }}"
        labels:
          # Add any desired labels here
        cloud_init:
          user_data:
            hostname: "{{ vm_name }}"
            network:
              version: 2
              ethernets:
                eth0:
                  dhcp4: true
                  nameservers:
                    addresses:
                      #Replace with your DNS servers
                      - 172.16.100.12
                      - 172.16.100.16
            resolv_conf:
              nameservers:
                #Replace with your DNS servers
                - 172.16.100.12
                - 172.16.100.16
            users:
              - name: ubuntu

                # To enable SSH key authentication, uncomment and add your public keys here
                #ssh_authorized_keys:
                #  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCy..."
                sudo: "ALL=(ALL) NOPASSWD:ALL"
                shell: /bin/bash
                # Password hashed using SHA-512 (generated raw with: mkpasswd --method=SHA-512)
                # Default password: ubuntu (change on first login)
                # You might have to install passlib to generate password hashes: apt install -y passlib or arch linux: pacman -S python-passlib
                # SECURITY WARNING: Using password_hash without a salt uses a random salt (recommended)
                # Alternatively, load salt from an encrypted vault file: "{{ 'ubuntu' | password_hash('sha512', lookup('ansible.builtin.env', 'PASSWORD_SALT')) }}"
                passwd: "{{ 'ubuntu' | password_hash('sha512') }}"
                lock_passwd: false
            package_update: true
            package_upgrade: true
            packages:
              - qemu-guest-agent
            runcmd:
              - systemctl enable --now qemu-guest-agent || true
        verify_ssl: "{{ harvester_verify_ssl }}"
      register: vm_result

    - name: Display VM information
      debug:
        msg: "VM '{{ vm_result.vm.metadata.name }}' has been {{ vm_result.message }}"
