---
# Example playbook: Manage VM lifecycle (start, stop, restart)
- name: Manage Harvester VM lifecycle
  hosts: localhost
  gather_facts: false
  vars:
    # Harvester settings will be loaded from .env file
    vm_name: "my-ubuntu-vm"


  pre_tasks:
    - name: Load Harvester settings from environment variables (use dotenv to export before running)
      set_fact:
        harvester_host: "{{ lookup('ansible.builtin.env', 'HARVESTER_HOST') }}"
        harvester_token: "{{ lookup('ansible.builtin.env', 'HARVESTER_TOKEN') }}"
        harvester_namespace: "{{ lookup('ansible.builtin.env', 'HARVESTER_NAMESPACE') | default('default') }}"
        harvester_verify_ssl: "{{ lookup('ansible.builtin.env', 'HARVESTER_VERIFY_SSL') | default('true') }}"
  
  tasks:
    - name: Stop the virtual machine
      bpmconsultag.harvester.harvester_vm:
        host: "{{ harvester_host }}"
        token: "{{ harvester_token }}"
        name: "{{ vm_name }}"
        namespace: "{{ harvester_namespace }}"
        state: stopped
      register: stop_result

    - name: Wait for VM to stop
      pause:
        seconds: 10

    - name: Start the virtual machine
      bpmconsultag.harvester.harvester_vm:
        host: "{{ harvester_host }}"
        token: "{{ harvester_token }}"
        name: "{{ vm_name }}"
        namespace: "{{ harvester_namespace }}"
        state: started
      register: start_result

    - name: Restart the virtual machine
      bpmconsultag.harvester.harvester_vm:
        host: "{{ harvester_host }}"
        token: "{{ harvester_token }}"
        name: "{{ vm_name }}"
        namespace: "{{ harvester_namespace }}"
        state: restarted
      register: restart_result

    - name: Display results
      debug:
        msg: "VM lifecycle operations completed successfully"
