---
# Syntax validation playbook
# This playbook tests the Ansible role structure without actually executing tasks
- name: Test Ansible role syntax
  hosts: localhost
  gather_facts: false
  

  pre_tasks:
    - name: Load Harvester settings from environment variables (use dotenv to export before running)
      set_fact:
        harvester_host: "{{ lookup('ansible.builtin.env', 'HARVESTER_HOST') }}"
        harvester_token: "{{ lookup('ansible.builtin.env', 'HARVESTER_TOKEN') }}"
        harvester_namespace: "{{ lookup('ansible.builtin.env', 'HARVESTER_NAMESPACE') | default('default') }}"
        harvester_verify_ssl: "{{ lookup('ansible.builtin.env', 'HARVESTER_VERIFY_SSL') | default('true') }}"

  tasks:
    - name: Display test information
      debug:
        msg: "This playbook tests the Ansible role syntax and structure"

    - name: Test harvester_vm module syntax (check mode)
      bpmconsultag.harvester.harvester_vm:
        host: "https://harvester.example.com"
        token: "test-token"
        name: "test-vm"
        state: present
      check_mode: true
      ignore_errors: true
      register: vm_test

    - name: Test harvester_image module syntax (check mode)
      bpmconsultag.harvester.harvester_image:
        host: "https://harvester.example.com"
        token: "test-token"
        name: "test-image"
        url: "https://example.com/image.img"
        state: present
      check_mode: true
      ignore_errors: true
      register: image_test

    - name: Test harvester_volume module syntax (check mode)
      bpmconsultag.harvester.harvester_volume:
        host: "https://harvester.example.com"
        token: "test-token"
        name: "test-volume"
        storage: "10Gi"
        state: present
      check_mode: true
      ignore_errors: true
      register: volume_test

    - name: Test harvester_network module syntax (check mode)
      bpmconsultag.harvester.harvester_network:
        host: "https://harvester.example.com"
        token: "test-token"
        name: "test-network"
        config:
          cniVersion: "0.3.1"
          type: "bridge"
        state: present
      check_mode: true
      ignore_errors: true
      register: network_test

    - name: Display results
      debug:
        msg: "All module syntax tests completed"
